---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
SilverStripe\View\SSViewer:
  theme: one-ring
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Highlight\App\SiteConfigExtension
SilverStripe\Blog\Model\Blog:
  extensions:
    - Highlight\App\BlogExtension
SilverStripe\Blog\Model\BlogPost:
  extensions:
    - Highlight\App\BlogPostExtension
SilverStripe\Blog\Model\BlogCategory:
  extensions:
    - Highlight\App\BlogCategoryExtension
---
Only:
  environment: dev
---
SilverStripe\Control\Email\Email:
  send_all_emails_to: me@example.com
---
Except:
  environment: dev
---
SilverStripe\Control\Email\Email:
  bcc_all_emails_to: me@example.com
